import Foundation

/// Loads the fixtures in Tests/Fixtures: anonymized captures of a real
/// macOS 26.6.2 system (no sudo), regenerated by scripts/anonymize-fixtures.py
/// from the git-ignored real captures in Tests/Fixtures/real.
enum Fixtures {
    static var directory: String {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // LaunchKeeperKitTests
            .deletingLastPathComponent()   // Tests
            .appendingPathComponent("Fixtures").path
    }

    static func exists(_ name: String) -> Bool {
        FileManager.default.fileExists(atPath: directory + "/" + name)
    }

    static func text(_ name: String) -> String {
        (try? String(contentsOfFile: directory + "/" + name, encoding: .utf8)) ?? ""
    }
}